language: go
go:
  - 1.3.1
  - tip

addons:
  postgresql: "9.3"

before_install:
  - util/commit-validator/validate-dco
  - util/commit-validator/validate-gofmt || test "$TRAVIS_GO_VERSION" = "tip"

install:
  - pushd /tmp

  - go install -race std
  - go get code.google.com/p/go.tools/cmd/cover

  - go install github.com/flynn/flynn/discoverd

  - wget https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz
  - tar xzf etcd-v0.4.6-linux-amd64.tar.gz
  - mv etcd-v0.4.6-linux-amd64/etcd $HOME/gopath/bin
  - export PATH=$HOME/gopath/bin:$PATH

  - sudo mkdir -p /usr/include/btrfs
  - sudo wget -O /usr/include/btrfs/ioctl.h https://raw.githubusercontent.com/josefbacik/btrfs-progs/master/ioctl.h

  - git clone --no-checkout https://git.fedorahosted.org/git/lvm2.git
  - pushd lvm2
  - git checkout -q v2_02_103
  - ./configure --enable-static_link
  - sudo make device-mapper
  - sudo make install_device-mapper
  - popd

  - wget http://libvirt.org/sources/libvirt-1.2.2.tar.gz
  - tar xzf libvirt-1.2.2.tar.gz
  - pushd libvirt-1.2.2
  - ./configure --prefix=/usr --without-apparmor --without-attr --without-audit --without-avahi --without-blkid --without-capng --without-curl --without-dbus --without-fuse --without-glusterfs --without-hal --without-netcf --without-numactl --without-openwsman --without-pciaccess --without-sanlock --without-sasl --without-selinux --without-ssh2 --without-systemd-daemon --without-udev --without-yajl --without-xen --without-xen-inotify --without-qemu --without-uml --without-openvz --without-vmware --without-phyp --without-xenapi --without-libxl --without-esx --without-hyperv --without-parallels --without-test --without-remote --without-libvirtd --without-bhyve --without-polkit --without-firewalld --without-dtrace --without-numad --without-network --without-secrets --without-storage-fs --without-storage-lvm --without-storage-iscsi --without-storage-scsi --without-storage-mpath --without-storage-disk --without-storage-rbd --without-storage-sheepdog --without-storage-gluster --without-test-suite --without-interface --without-macvtap --without-virtualport --without-wireshark-dissector --without-vbox
  - make
  - sudo make install
  - popd

  - psql -c 'create database blobstoretest;' -U postgres
  - export PGUSER=postgres

  - popd

script:
  - DEBUG=1 go test -race -cover ./... -test.v
  - cd router && DEBUG=1 go test -race -fake=false -check.v

notifications:
  irc:
    channels:
      - "chat.freenode.net#flynn"
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch} - %{commit}: %{message} %{build_url}"

matrix:
  allow_failures:
    - go: tip
